CREATE TABLE `voting_sys`.`users` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DO USUARIO',
    `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NOME DO USUARIO',
    `cpf` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CPF DO USUARIO',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'TABELA DE USUARIOS REGISTRADOS PARA VOTAÇÃO';