CREATE TABLE `voting_sys`.`users` (
    `user_id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DO USUARIO',
    `user_name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NOME DO USUARIO',
    `user_cpf` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CPF DO USUARIO',
    PRIMARY KEY (`user_id`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'TABELA DE USUARIOS REGISTRADOS PARA VOTAÇÃO';
