-- DB E TABELA DE CANDIDATOS--
CREATE TABLE `voting_sys`.`products` (`id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DO ITEM',
 `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NOME DO ITEM',
 `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DESCRIÇÃO DO ITEM',
 `image` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'IMAGEM DO ITEM',
 `votes` INT(255) NOT NULL COMMENT 'VOTOS DO ITEM', 
 PRIMARY KEY (`id`)) 
 ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'TABELA DE PRODUTOS(CANDITATOS)';

-- ALTERAR O TAMANHO DE VOTES PRA O MAXIMO 255 --
ALTER TABLE `products` CHANGE `votes` `votes` INT(255) NOT NULL COMMENT 'VOTOS DO ITEM';