CREATE TABLE `voting_sys`.`products` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DO PRODUTO',
    `name` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NOME DO PRODUTO',
    `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DESCRIÇÃO DO PRODUTO',
    `number` INT(255) NOT NULL COMMENT 'NUMERO DO PRODUTO',
    `image` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'IMAGEM DO PRODUTO',
    `votes` INT NOT NULL COMMENT 'NUM. DE VOTOS DO PRODUTO',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARSET = utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'TABELA DE PRODUTOS';


ALTER TABLE products DROP COLUMN votes;