-- TABLE DE USUARIOS ADMINISTRADORES--
CREATE TABLE `voting_sys`.`admins` (`id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID DA CONTA',
 `email` TEXT NOT NULL COMMENT 'EMAIL DA CONTA',
 `password` TEXT NOT NULL COMMENT 'SENHA DA CONTA',
 `type` TEXT NOT NULL COMMENT 'TIPO DA CONTA',
 PRIMARY KEY (`id`))
 ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT = 'TABELA DE CONTAS DE USUARIO';